### ISSUE TITLE
 Link to IP Allowlist Documentation is Broken / Can't Find Outbound IP Addresses

### ISSUE THREAD

**Issue by nathanjones4323** [streamlit/docs#616]
### Summary

The links to [Stable outbound IP address - Streamlit Docs ](https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/stable-outbound-ip-addresses#allowlisting-streamlits-outbound-ip-addresses)in the documentation and discussion thread is broken. It takes you to the “[Get Started](https://docs.streamlit.io/streamlit-community-cloud/get-started)” page instead

There is no longer a page or section with this title.

I also could not find the IP addresses when searching for keywords on Google and on the docs page

**Comment by snehankekre** [comment]
Hi @nathanjones4323 👋 

Thank your for submitting this issue. As we've responded in the [forum post](https://discuss.streamlit.io/t/link-to-ip-allowlist-documentation-is-broken/40648/2?u=snehankekre), this is a feature we retired/sunset for Community Cloud and, as such, took down the docs page.

**Comment by nathanjones4323** [comment]
Does this mean you are not going to support the IP Allowlisting for Private Community Cloud Apps?

I have a Private Community Cloud App up right now that connects to a AWS database, so I need to use the IP Allowlist to communicate with the DB.

I've tried SSH tunneling, but that won't work for me right now.

If I want to continue using my private app and have it communicate with the database do I need to move to a self hosted solution?

**Comment by snehankekre** [comment]
I would suggest taking it up in the linked forum thread 😅 The Stable outbound IP addresses feature was sunset as it falls under the enterprise/business umbrella, so docs for it no longer exist. 

That said, the Community Cloud team is doing more discovery with community members such as yourself to dig into how they're using it and if that use case makes sense for the new direction of Community Cloud, which is why I recommend sharing your use-cases and requests for alternative solutions with [@tc1](https://discuss.streamlit.io/u/tc1) on the [forum](https://discuss.streamlit.io/t/link-to-ip-allowlist-documentation-is-broken/40648/2?u=snehankekre).
