### ISSUE TITLE
Not Documented: Streamlit Cloud force-installs protobuf 3.20.1

### ISSUE THREAD

**Issue by MathCatsAnd** [streamlit/docs#639]
There are a lot of posts involving protobuf versions on the forum. Per @blackary in [this post](https://discuss.streamlit.io/t/why-is-protobuf-forced-installed-in-version-3-20-1/42150/16?u=mathcatsand), Streamlit Cloud force-installs protobuf 3.20.1 and this should be documented.

This seems like a good note to add here: https://docs.streamlit.io/streamlit-community-cloud/get-started/deploy-an-app/app-dependencies

Nothing is coming up when I search the docs for protobuf, so a KB article may also be good that can be linked from said note. I'm not sure how often Streamlit Cloud changes what version of protobuf is forced. Is it sufficient to just note the current forced version and to advise marking it down as pinned to force pip to resolve the rest correctly?

**Comment by snehankekre** [comment]
Thank you for triaging this issue from the forum post, @MathCatsAnd! There was an internal discussion related to this issue a few days ago. Here's the summary:
- Streamlit core pins: protobuf<4,>=3.12 . Unfortunately, we still don't support protobuf 4.x. It's a bit more complicated to update that, but we have that planned as a project in Q2
- We could allow everything <4 on Streamlit cloud as well. We believe the reason was that there was a broken protobuf release distribution (3.20.2 ), but which was resolved a short time later, see the PRs [here](https://github.com/streamlit/streamlit/pull/5396) and [here](https://github.com/streamlit/streamlit/pull/5478). Maybe that is the reason why it was pinned in Cloud as well. If that was the case, we can remove this since the issue doesn't exist anymore with any of the 3.20.x releases
- @blackary has an open PR in the Cloud repo to install a "Streamlit compatible" version of protobuf on Cloud. i.e. `pip install "protobuf<4,>=3.12"` and don't hard-pin protobuf. https://github.com/streamlit/s4t/pull/5339/files

The PR fixing this issue could callout that users can install protobuf or dependencies that install protobuf as long as the versions are compatible with those of the Streamlit library (`protobuf<4,>=3.12`).

**Comment by MathCatsAnd** [comment]
If the hidden restriction is to be removed, does it still make sense to mention anything? At that point it's not really anything to do with Streamlit Cloud specifically and just a note for any Streamlit app deployed anywhere to take note of the protobuf restriction and plan your other packages accordingly.

But since the Streamlit Cloud section is in fact where app dependencies are discussed right now, the note at the bottom of the [app dependencies](https://docs.streamlit.io/streamlit-community-cloud/get-started/deploy-an-app/app-dependencies) page could be:
before
>Only include packages in your requirements file that are not distributed with a standard Python installation. If [any of the modules from base Python](https://docs.python.org/3/py-modindex.html) are included in the requirements file, you will get an error when you try to deploy. Additionally, we recommend that you use the latest version of Streamlit to ensure full Streamlit Community Cloud functionality.


after
>Only include packages in your requirements file that are not distributed with a standard Python installation. If [any of the modules from base Python](https://docs.python.org/3/py-modindex.html) are included in the requirements file, you will get an error when you try to deploy. Additionally, we recommend that you use the latest version of Streamlit to ensure full Streamlit Community Cloud functionality. Be sure to take note of Streamlit's [current requirements](https://github.com/streamlit/streamlit/blob/develop/lib/dev-requirements.txt) for package compatibility when planning your environment, especially `protobuf<4,>=3.12`.

**Comment by snehankekre** [comment]
The proposed edited note in the Streamlit Cloud section makes sense to me. If we also want to call out the protobuf restriction in the Streamlit library section, it would make most sense to talk about it when explaining constraint files in  https://github.com/streamlit/docs/pull/620
