### ISSUE TITLE
Text input box is not getting empty after pressing enter key

### ISSUE THREAD

**Issue by MohdFaizanSaifi** [streamlit/docs#823]
### Summary

When a user utilizes the text_input method from the Streamlit library, the text area is not automatically cleared after pressing the Enter key following the text entry, which may be considered unexpected behavior.

### Steps to reproduce

Code snippet:

st.text_input("Ask a question from the documents:")

Screenshot(s):

(Please provide a code snippet and/or screenshots! These will help expedite us finding and solving the problem.)

If applicable, please provide the steps we should take to reproduce the bug:

1. Import the Streamlit library in Python, then utilize its text_input function.
2. Run the Streamlit app and enter content in the input box visible in the browser.
3. After pressing the Enter key, the input box does not automatically clear itself, which is an unexpected behavior.

**Expected behavior:**

After pressing the Enter key, the input box should automatically clear itself.

**Actual behavior:**

<img width="566" alt="issue_github" src="https://github.com/streamlit/docs/assets/113685650/c683e461-539d-4fbf-aa46-0b08c2605546">

### Is this a regression?

That is, did this use to work the way you expected in the past?
No

### Debug info

- Docs page link: (do you have a link to the docs page containing the bug?)
- npm version: (get it with `npm -v`)
- node version: (get it with `node -v`)
- OS version:
- Browser version:

### Additional information

If needed, add any other context about the problem here. For example, did this bug come from <https://discuss.streamlit.io> or another site? Link the original source here!

**Comment by sfc-gh-dmatthews** [comment]
Hi @MohdFaizanSaifi! 👋🏻  Thanks for raising your concern. This is expected behavior. Widgets are meant to be stateful by default so typing in information and pressing enter (or clicking outside the widget) will simply update the widget with the new, entered value. If you need to clear a widget after submitting info, you would need to update the widget's value through Session State or use [`st.form`](https://docs.streamlit.io/library/api-reference/control-flow/st.form) with `clear_on_submit=True`.

I'll close this issue, but if you have any further questions you can [reach out on the forums](https://discuss.streamlit.io/) for more guidance.
