### ISSUE TITLE
Licensing: Is it required to show the streamlit branding and other dependency information in a streamlit app?

### ISSUE THREAD

**Issue by stefaneidelloth** [streamlit/docs#890]
**a)** Could you please clarify in the documentation, it it is allowed to remove/hide the StreamLit **branding** or if that
would violate your license terms? Also see related discussion here:
https://discuss.streamlit.io/t/remove-made-with-streamlit-from-bottom-of-app/1370/21

**b)** Furthermore, If a third party dependency (for example with Apache or AGPL license) is used for a StreamLit app, how should it be **properly mentioned** in the app? Is there already some sort of license-notice component that would automatically generate some info-window from pyproject.toml, requirements.txt and/or NOTICES file and show it to the **end users** (for example under burger menu => About)? If that is required at all?

Related:

https://opensource.stackexchange.com/a/12106/30658

https://github.com/streamlit/streamlit/blob/develop/NOTICES

https://github.com/streamlit/streamlit/blob/develop/LICENSE

**Comment by fhg-isi** [comment]
Maybe related: https://softwareengineering.stackexchange.com/questions/234511/what-is-the-best-practice-for-arranging-third-party-library-licenses-paperwork

**Comment by sfc-gh-dmatthews** [comment]
Since this question was asked, we've actually removed the "Made with Streamlit" footer. Also, the configuration options provided within the library allow the toolbar and App menu to be removed, so there's no branding within the library that can't be hidden with native Streamlit features. These options should all be documented now, so I think this request is covered.

There is an icon in the lower right corner for apps hosted on Streamlit Community Cloud, but this is part of the platform, not the app. It can't be accessed or modified from app code and is a functional part of the hosting platform.

---

As for licensing, when you use a published version of Streamlit, the license is included in the body of Streamlit's code without a need to surface it to your end user. That is, if you are using Streamlit as most people do, the licensing information is appropriately included with every installation of the software (`pip install streamlit`). Streamlit's direct dependencies are similar and we monitor these direct dependencies for any changes to their licensing.

However, we can't advise you about any other dependencies in your app as you'll have to read and follow whatever licensing terms they have. Generally, if you start copying and modifying code from other work, licensing requirements will become more complicated. For Streamlit, most people are using it as-is rather than modifying the library itself, so that doesn't come up as often.
